services:
  postgres:
    container_name: ll-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ll
    ports:
      - "5437:5432"
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data

networks:
  shared_network:
    driver: bridge
