services:
  postgres:
    container_name: ll-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ll
    ports:
      - "5437:5432"
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data

  # Envoy proxy service
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080" # Expose the Envoy proxy port
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro # Mount the Envoy configuration
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
