packages:
    - apps/*
    - packages/*
catalog:
    # next
    "next": "15.1.5"
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "typescript": "^5.0.0"
    "@types/node": "^20"
    "@types/react": "^19"
    "@types/react-dom": "^19"
    "tailwindcss": "^3.4.1"
    "eslint": "^9.0.0"
    "eslint-config-next": "15.1.5"
    "@eslint/eslintrc": "^3.0.0"
    "@next/env": "^15.1.6"

    # mantine
    "@mantine/carousel": "^7.16.2"
    "@mantine/charts": "^7.16.2"
    "@mantine/code-highlight": "^7.16.2"
    "@mantine/core": "^7.16.2"
    "@mantine/dates": "^7.16.2"
    "@mantine/dropzone": "^7.16.2"
    "@mantine/form": "^7.16.2"
    "@mantine/hooks": "^7.16.2"
    "@mantine/modals": "^7.16.2"
    "@mantine/notifications": "^7.16.2"
    "@mantine/nprogress": "^7.16.2"
    "@mantine/spotlight": "^7.16.2"
    "@mantine/tiptap": "^7.16.2"
    "@tabler/icons-react": "^3.29.0"
    "@tiptap/extension-link": "^2.11.3"
    "@tiptap/pm": "^2.11.3"
    "@tiptap/react": "^2.11.3"
    "@tiptap/starter-kit": "^2.11.3"
    "dayjs": "^1.11.13"
    "embla-carousel-react": "^7.1.0"
    "recharts": "2.0.0"
    "postcss": "^8.5.1"
    "postcss-preset-mantine": "^1.17.0"
    "postcss-simple-vars": "^7.0.1"

    # grpc
    "@grpc/grpc-js": "^1.12.6"
    "dotenv": "^16.4.7"
    "google-protobuf": "^3.21.4"
    "next-client-cookies": "^2.0.1"
    "@types/google-protobuf": "^3.15.12"
