import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createTheme, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { CookiesProvider } from "next-client-cookies/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CookiesProvider>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
