// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chapter_content.proto

package chapter_content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_chapter_content_proto protoreflect.FileDescriptor

const file_chapter_content_proto_rawDesc = "" +
	"\n" +
	"\x15chapter_content.proto\x12\x0fchapter_contentBEZCgithub.com/saiponethaaung/language-learner/apps/api/chapter_contentb\x06proto3"

var file_chapter_content_proto_goTypes = []any{}
var file_chapter_content_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chapter_content_proto_init() }
func file_chapter_content_proto_init() {
	if File_chapter_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_content_proto_rawDesc), len(file_chapter_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chapter_content_proto_goTypes,
		DependencyIndexes: file_chapter_content_proto_depIdxs,
	}.Build()
	File_chapter_content_proto = out.File
	file_chapter_content_proto_goTypes = nil
	file_chapter_content_proto_depIdxs = nil
}
