// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

export interface ErrorResponse {
  code: string;
  message: string;
}

export interface EmptyRequest {
}

export interface IDRequest {
  id: string;
}

export interface IntIDRequest {
  id: number;
}

export interface StatusResponse {
  status: boolean;
  message: string;
}

export interface PaginationObject {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}
