// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: course.proto

/* eslint-disable */
import { type IDRequest, type IntIDRequest, type PaginationObject, type StatusResponse } from "./common";

export const protobufPackage = "course";

export interface CreateCourseRequest {
  languageID: number;
  courseLanguageID: number;
  name: string;
}

export interface UpdateCourseRequet {
  languageID: number;
  courseLanguageID: number;
  status: number;
  name: string;
}

export interface CourseObject {
  id: number;
  languageID: number;
  courseLanguageID: number;
  status: number;
  createdAt: string;
  updatedAt: string;
  name: string;
}

export interface PaginationResponse {
  data: CourseObject[];
  pagination: PaginationObject | undefined;
}

export interface GetCourseRequest {
  page: number;
  limit: number;
}

export interface CourseService {
  Create(request: CreateCourseRequest): Promise<CourseObject>;
  Get(request: IntIDRequest): Promise<CourseObject>;
  GetAll(request: GetCourseRequest): Promise<PaginationResponse>;
  Update(request: UpdateCourseRequet): Promise<CourseObject>;
  Delete(request: IDRequest): Promise<StatusResponse>;
}
