// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.1
// source: course.proto

/* eslint-disable */
import { type EmptyRequest, type IDRequest, type IntIDRequest, type StatusResponse } from "./common";

export const protobufPackage = "course";

export interface CreateCourse {
  targetLanguageID: number;
  sourceLanguageID: number;
}

export interface UpdateCourse {
  targetLanguageID: number;
  sourceLanguageID: number;
  status: boolean;
}

export interface CourseObject {
  id: number;
  targetLanguageID: number;
  sourceLanguageID: number;
  status: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CourseService {
  Create(request: CreateCourse): Promise<CourseObject>;
  Get(request: IntIDRequest): Promise<CourseObject>;
  GetAll(request: EmptyRequest): Promise<CourseObject>;
  Update(request: UpdateCourse): Promise<CourseObject>;
  Delete(request: IDRequest): Promise<StatusResponse>;
}
