// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.1
// source: language.proto

/* eslint-disable */
import { type EmptyRequest, type IntIDRequest, type PaginationObject } from "./common";

export const protobufPackage = "language";

export interface GetLanguagesRequest {
  page: number;
  limit: number;
}

export interface CreateLanguageRequest {
  name: string;
  code: string;
}

export interface UpdateLanguageRequest {
  id: number;
  name: string;
  code: string;
}

export interface UpdateLanguageStatusRequest {
  id: number;
  status: boolean;
}

export interface LanguageObject {
  id: number;
  name: string;
  code: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaginationResponse {
  data: LanguageObject[];
  pagination: PaginationObject | undefined;
}

export interface LanguageService {
  GetLanguages(request: GetLanguagesRequest): Promise<PaginationResponse>;
  GetLanguage(request: IntIDRequest): Promise<LanguageObject>;
  CreateLanguage(request: CreateLanguageRequest): Promise<LanguageObject>;
  UpdateLanguage(request: UpdateLanguageRequest): Promise<LanguageObject>;
  UpdateLanguageStatus(request: UpdateLanguageStatusRequest): Promise<LanguageObject>;
  DeleteLanguage(request: IntIDRequest): Promise<EmptyRequest>;
}
