// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: section.proto

/* eslint-disable */
import { type IntIDRequest, type PaginationObject } from "./common";

export const protobufPackage = "section";

export interface CreateSectionRequest {
  courseID: number;
  name: string;
}

export interface SectionObject {
  id: number;
  name: string;
  courseID: number;
}

export interface PaginationResponse {
  data: SectionObject[];
  pagination: PaginationObject | undefined;
}

export interface GetSectionRequest {
  page: number;
  limit: number;
}

export interface SectionService {
  Create(request: CreateSectionRequest): Promise<SectionObject>;
  GetAll(request: GetSectionRequest): Promise<PaginationResponse>;
  Get(request: IntIDRequest): Promise<SectionObject>;
}
