// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: section_unit.proto

/* eslint-disable */
import { type IntIDRequest, type PaginationObject } from "./common";

export const protobufPackage = "section_unit";

export interface CreateSectionUnitRequest {
  sectionID: number;
  name: string;
}

export interface SectionUnitObject {
  id: number;
  name: string;
  sectionID: number;
}

export interface PaginationResponse {
  data: SectionUnitObject[];
  pagination: PaginationObject | undefined;
}

export interface GetSectionUnitRequest {
  page: number;
  limit: number;
  sectionID: number;
}

export interface SectionUnitService {
  Create(request: CreateSectionUnitRequest): Promise<SectionUnitObject>;
  GetAll(request: GetSectionUnitRequest): Promise<PaginationResponse>;
  Get(request: IntIDRequest): Promise<SectionUnitObject>;
}
