// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.1
// source: user.proto

/* eslint-disable */
import { type EmptyRequest, type ErrorResponse } from "./common";

export const protobufPackage = "user";

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  status: boolean;
  accessToken?: string | undefined;
  error?: ErrorResponse | undefined;
}

export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
}

export interface RegisterResponse {
  status: boolean;
  message?: string | undefined;
  error?: ErrorResponse | undefined;
}

export interface UserObject {
  id: number;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}

export interface UserService {
  Login(request: LoginRequest): Promise<LoginResponse>;
  Register(request: RegisterRequest): Promise<RegisterResponse>;
  Profile(request: EmptyRequest): Promise<UserObject>;
}
