export enum Routes {
  Home = "/",
  Languages = "/languages",
  Security = "/security",
  Users = "/users",
  User = "/users/:id",
  NotFound = "/404",
  Courses = "/courses",
  Course = "/courses/:id",
  Sections = "/courses/:id/section",
  Section = "/courses/:id/section/:sectionID",
  Units = "/courses/:id/section/:sectionID/unit",
  Materials = "/courses/:id/material",
  Account = "/account",
  Settings = "/settings",
  Releases = "/releases",
  Login = "/login",
  Logout = "/logout",
  Register = "/register",
  ForgotPassword = "/forgot-password",
  ResetPassword = "/reset-password",
  VerifyEmail = "/verify-email",
}
