// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: chapter.proto

package chapter

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// ChapterServiceClient is the client API for ChapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChapterServiceClient interface {
}

type chapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChapterServiceClient(cc grpc.ClientConnInterface) ChapterServiceClient {
	return &chapterServiceClient{cc}
}

// ChapterServiceServer is the server API for ChapterService service.
// All implementations must embed UnimplementedChapterServiceServer
// for forward compatibility.
type ChapterServiceServer interface {
	mustEmbedUnimplementedChapterServiceServer()
}

// UnimplementedChapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChapterServiceServer struct{}

func (UnimplementedChapterServiceServer) mustEmbedUnimplementedChapterServiceServer() {}
func (UnimplementedChapterServiceServer) testEmbeddedByValue()                        {}

// UnsafeChapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChapterServiceServer will
// result in compilation errors.
type UnsafeChapterServiceServer interface {
	mustEmbedUnimplementedChapterServiceServer()
}

func RegisterChapterServiceServer(s grpc.ServiceRegistrar, srv ChapterServiceServer) {
	// If the following call pancis, it indicates UnimplementedChapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChapterService_ServiceDesc, srv)
}

// ChapterService_ServiceDesc is the grpc.ServiceDesc for ChapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chapter.ChapterService",
	HandlerType: (*ChapterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "chapter.proto",
}
