// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: course.proto

package course

import (
	common "github.com/saiponethaaung/language-learner/apps/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LanguageID       int32                  `protobuf:"varint,1,opt,name=languageID,proto3" json:"languageID,omitempty"`
	CourseLanguageID int32                  `protobuf:"varint,2,opt,name=courseLanguageID,proto3" json:"courseLanguageID,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetLanguageID() int32 {
	if x != nil {
		return x.LanguageID
	}
	return 0
}

func (x *CreateCourseRequest) GetCourseLanguageID() int32 {
	if x != nil {
		return x.CourseLanguageID
	}
	return 0
}

func (x *CreateCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCourseRequet struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LanguageID       int32                  `protobuf:"varint,1,opt,name=languageID,proto3" json:"languageID,omitempty"`
	CourseLanguageID int32                  `protobuf:"varint,2,opt,name=courseLanguageID,proto3" json:"courseLanguageID,omitempty"`
	Status           int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCourseRequet) Reset() {
	*x = UpdateCourseRequet{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequet) ProtoMessage() {}

func (x *UpdateCourseRequet) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequet.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequet) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCourseRequet) GetLanguageID() int32 {
	if x != nil {
		return x.LanguageID
	}
	return 0
}

func (x *UpdateCourseRequet) GetCourseLanguageID() int32 {
	if x != nil {
		return x.CourseLanguageID
	}
	return 0
}

func (x *UpdateCourseRequet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateCourseRequet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CourseObject struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LanguageID       int32                  `protobuf:"varint,2,opt,name=languageID,proto3" json:"languageID,omitempty"`
	CourseLanguageID int32                  `protobuf:"varint,3,opt,name=courseLanguageID,proto3" json:"courseLanguageID,omitempty"`
	Status           int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Name             string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CourseObject) Reset() {
	*x = CourseObject{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseObject) ProtoMessage() {}

func (x *CourseObject) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseObject.ProtoReflect.Descriptor instead.
func (*CourseObject) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *CourseObject) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseObject) GetLanguageID() int32 {
	if x != nil {
		return x.LanguageID
	}
	return 0
}

func (x *CourseObject) GetCourseLanguageID() int32 {
	if x != nil {
		return x.CourseLanguageID
	}
	return 0
}

func (x *CourseObject) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CourseObject) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CourseObject) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CourseObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PaginationResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          []*CourseObject          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationObject `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetData() []*CourseObject {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaginationResponse) GetPagination() *common.PaginationObject {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCourseRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\x06course\x1a\fcommon.proto\"u\n" +
	"\x13CreateCourseRequest\x12\x1e\n" +
	"\n" +
	"languageID\x18\x01 \x01(\x05R\n" +
	"languageID\x12*\n" +
	"\x10courseLanguageID\x18\x02 \x01(\x05R\x10courseLanguageID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x8c\x01\n" +
	"\x12UpdateCourseRequet\x12\x1e\n" +
	"\n" +
	"languageID\x18\x01 \x01(\x05R\n" +
	"languageID\x12*\n" +
	"\x10courseLanguageID\x18\x02 \x01(\x05R\x10courseLanguageID\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xd2\x01\n" +
	"\fCourseObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"languageID\x18\x02 \x01(\x05R\n" +
	"languageID\x12*\n" +
	"\x10courseLanguageID\x18\x03 \x01(\x05R\x10courseLanguageID\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"x\n" +
	"\x12PaginationResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.course.CourseObjectR\x04data\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.common.PaginationObjectR\n" +
	"pagination\"<\n" +
	"\x10GetCourseRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\xba\x02\n" +
	"\rCourseService\x12=\n" +
	"\x06Create\x12\x1b.course.CreateCourseRequest\x1a\x14.course.CourseObject\"\x00\x123\n" +
	"\x03Get\x12\x14.common.IntIDRequest\x1a\x14.course.CourseObject\"\x00\x12@\n" +
	"\x06GetAll\x12\x18.course.GetCourseRequest\x1a\x1a.course.PaginationResponse\"\x00\x12<\n" +
	"\x06Update\x12\x1a.course.UpdateCourseRequet\x1a\x14.course.CourseObject\"\x00\x125\n" +
	"\x06Delete\x12\x11.common.IDRequest\x1a\x16.common.StatusResponse\"\x00B<Z:github.com/saiponethaaung/language-learner/apps/api/courseb\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_course_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),     // 0: course.CreateCourseRequest
	(*UpdateCourseRequet)(nil),      // 1: course.UpdateCourseRequet
	(*CourseObject)(nil),            // 2: course.CourseObject
	(*PaginationResponse)(nil),      // 3: course.PaginationResponse
	(*GetCourseRequest)(nil),        // 4: course.GetCourseRequest
	(*common.PaginationObject)(nil), // 5: common.PaginationObject
	(*common.IntIDRequest)(nil),     // 6: common.IntIDRequest
	(*common.IDRequest)(nil),        // 7: common.IDRequest
	(*common.StatusResponse)(nil),   // 8: common.StatusResponse
}
var file_course_proto_depIdxs = []int32{
	2, // 0: course.PaginationResponse.data:type_name -> course.CourseObject
	5, // 1: course.PaginationResponse.pagination:type_name -> common.PaginationObject
	0, // 2: course.CourseService.Create:input_type -> course.CreateCourseRequest
	6, // 3: course.CourseService.Get:input_type -> common.IntIDRequest
	4, // 4: course.CourseService.GetAll:input_type -> course.GetCourseRequest
	1, // 5: course.CourseService.Update:input_type -> course.UpdateCourseRequet
	7, // 6: course.CourseService.Delete:input_type -> common.IDRequest
	2, // 7: course.CourseService.Create:output_type -> course.CourseObject
	2, // 8: course.CourseService.Get:output_type -> course.CourseObject
	3, // 9: course.CourseService.GetAll:output_type -> course.PaginationResponse
	2, // 10: course.CourseService.Update:output_type -> course.CourseObject
	8, // 11: course.CourseService.Delete:output_type -> common.StatusResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
