// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: section_unit.proto

package section_unit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_section_unit_proto protoreflect.FileDescriptor

const file_section_unit_proto_rawDesc = "" +
	"\n" +
	"\x12section_unit.proto\x12\fsection_unit2\x14\n" +
	"\x12SectionUnitServiceBBZ@github.com/saiponethaaung/language-learner/apps/api/section_unitb\x06proto3"

var file_section_unit_proto_goTypes = []any{}
var file_section_unit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_section_unit_proto_init() }
func file_section_unit_proto_init() {
	if File_section_unit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_section_unit_proto_rawDesc), len(file_section_unit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_section_unit_proto_goTypes,
		DependencyIndexes: file_section_unit_proto_depIdxs,
	}.Build()
	File_section_unit_proto = out.File
	file_section_unit_proto_goTypes = nil
	file_section_unit_proto_depIdxs = nil
}
