// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: section.proto

package section

import (
	common "github.com/saiponethaaung/language-learner/apps/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseID      int32                  `protobuf:"varint,1,opt,name=courseID,proto3" json:"courseID,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSectionRequest) GetCourseID() int32 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *CreateSectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SectionObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CourseID      int32                  `protobuf:"varint,3,opt,name=courseID,proto3" json:"courseID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionObject) Reset() {
	*x = SectionObject{}
	mi := &file_section_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionObject) ProtoMessage() {}

func (x *SectionObject) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionObject.ProtoReflect.Descriptor instead.
func (*SectionObject) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{1}
}

func (x *SectionObject) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SectionObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SectionObject) GetCourseID() int32 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          []*SectionObject         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationObject `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_section_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationResponse) GetData() []*SectionObject {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaginationResponse) GetPagination() *common.PaginationObject {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectionRequest) Reset() {
	*x = GetSectionRequest{}
	mi := &file_section_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionRequest) ProtoMessage() {}

func (x *GetSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionRequest.ProtoReflect.Descriptor instead.
func (*GetSectionRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{3}
}

func (x *GetSectionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSectionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_section_proto protoreflect.FileDescriptor

const file_section_proto_rawDesc = "" +
	"\n" +
	"\rsection.proto\x12\asection\x1a\fcommon.proto\"F\n" +
	"\x14CreateSectionRequest\x12\x1a\n" +
	"\bcourseID\x18\x01 \x01(\x05R\bcourseID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"O\n" +
	"\rSectionObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcourseID\x18\x03 \x01(\x05R\bcourseID\"z\n" +
	"\x12PaginationResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.section.SectionObjectR\x04data\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.common.PaginationObjectR\n" +
	"pagination\"=\n" +
	"\x11GetSectionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\x98\x01\n" +
	"\x0eSectionService\x12A\n" +
	"\x06Create\x12\x1d.section.CreateSectionRequest\x1a\x16.section.SectionObject\"\x00\x12C\n" +
	"\x06GetAll\x12\x1a.section.GetSectionRequest\x1a\x1b.section.PaginationResponse\"\x00B=Z;github.com/saiponethaaung/language-learner/apps/api/sectionb\x06proto3"

var (
	file_section_proto_rawDescOnce sync.Once
	file_section_proto_rawDescData []byte
)

func file_section_proto_rawDescGZIP() []byte {
	file_section_proto_rawDescOnce.Do(func() {
		file_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)))
	})
	return file_section_proto_rawDescData
}

var file_section_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_section_proto_goTypes = []any{
	(*CreateSectionRequest)(nil),    // 0: section.CreateSectionRequest
	(*SectionObject)(nil),           // 1: section.SectionObject
	(*PaginationResponse)(nil),      // 2: section.PaginationResponse
	(*GetSectionRequest)(nil),       // 3: section.GetSectionRequest
	(*common.PaginationObject)(nil), // 4: common.PaginationObject
}
var file_section_proto_depIdxs = []int32{
	1, // 0: section.PaginationResponse.data:type_name -> section.SectionObject
	4, // 1: section.PaginationResponse.pagination:type_name -> common.PaginationObject
	0, // 2: section.SectionService.Create:input_type -> section.CreateSectionRequest
	3, // 3: section.SectionService.GetAll:input_type -> section.GetSectionRequest
	1, // 4: section.SectionService.Create:output_type -> section.SectionObject
	2, // 5: section.SectionService.GetAll:output_type -> section.PaginationResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_section_proto_init() }
func file_section_proto_init() {
	if File_section_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_section_proto_goTypes,
		DependencyIndexes: file_section_proto_depIdxs,
		MessageInfos:      file_section_proto_msgTypes,
	}.Build()
	File_section_proto = out.File
	file_section_proto_goTypes = nil
	file_section_proto_depIdxs = nil
}
